services:
  app:
    build:
      context: .
      args:
        NEXT_PUBLIC_CDP_WRITEKEY: ${NEXT_PUBLIC_CDP_WRITEKEY}
        NEXT_PUBLIC_CDP_ENDPOINT: ${NEXT_PUBLIC_CDP_ENDPOINT}
        NEXT_PUBLIC_DISCOVER_DEFAULT_SCRIPT: ${NEXT_PUBLIC_DISCOVER_DEFAULT_SCRIPT}
    image: demo-banking
    container_name: banking-app
    ports:
      - "3100:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_CDP_WRITEKEY=${NEXT_PUBLIC_CDP_WRITEKEY}
      - NEXT_PUBLIC_CDP_ENDPOINT=${NEXT_PUBLIC_CDP_ENDPOINT}
      - NEXT_PUBLIC_DISCOVER_DEFAULT_SCRIPT=${NEXT_PUBLIC_DISCOVER_DEFAULT_SCRIPT}
    depends_on:
      - database
    command: ["npm", "run", "start"]

  database:
    image: postgres:16
    container_name: banking-database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
