# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  release:
    types:
      - created
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --build-arg NEXT_PUBLIC_CDP_WRITEKEY=${{ secrets.NEXT_PUBLIC_CDP_WRITEKEY }} --build-arg NEXT_PUBLIC_CDP_ENDPOINT=${{ secrets.NEXT_PUBLIC_CDP_ENDPOINT }} --build-arg NEXT_PUBLIC_DISCOVER_DEFAULT_SCRIPT=${{ secrets.NEXT_PUBLIC_DISCOVER_DEFAULT_SCRIPT }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
